vikejs/vike-react

CHANGELOG.md
CONTRIBUTING.md
vike-react/renderer/+config.ts

docs: Document how to release a new version

---

.github/workflows/build.yml
package.json

@AurelienLourot FYI omitting `with: version` will make `pnpm/action-setup@v2` pick `package.json#packageManager`.

improve CI

---

vike-react/README.md

docs: improve readme

---

.github/workflows/build.yml
examples/basic/package.json
examples/ssr-spa/package.json

Aligning with https://github.com/magne4000/vike-solid
See https://github.com/magne4000/vike-solid/pull/14

qual: run `pnpm run test` in CI instead of tsc directly

---

vike-react/README.md

See https://github.com/brillout/vite-plugin-ssr/pull/1135

docs: mention the V1 design

---

pnpm-lock.yaml
vike-react/package.json
vike-react/renderer/+config.ts
vike-react/renderer/PageContextProvider.tsx
vike-react/renderer/getPageElement.tsx
vike-react/renderer/onRenderClient.tsx
vike-react/renderer/onRenderHtml.tsx
vike-react/renderer/types.ts

Declaration merging now also works for `PageContext`.
@magne4000 @AurelienLourot

fix: use Vike.PageContext

---

examples/basic/package.json
examples/basic/pages/star-wars/@id/+onBeforeRender.ts
examples/basic/pages/star-wars/index/+onBeforeRender.ts
examples/ssr-spa/package.json
pnpm-lock.yaml
vike-react/package.json
vike-react/renderer/+config.ts
vike-react/renderer/getPageElement.tsx
vike-react/renderer/getTitle.ts
vike-react/renderer/types.ts

Added useful types and comments.
Spin-off of https://github.com/vikejs/vike-react/pull/10

qual: improvements around getTitle

---

vike-react/renderer/onRenderHtml.tsx

@brillout what do you think of this?

feat: add link to repo to SSR shell

---

vike-react/renderer/getPageElement.tsx
vike-react/renderer/onRenderHtml.tsx

Follow-up on #33 
CC @nitedani

fix: don't use react-streaming when SSR is disabled

---

.github/workflows/build.yml

qual: add react-query example to CI

---

examples/basic/package.json
examples/react-query/package.json
examples/react-query/pages/index/Movies.tsx
examples/react-query/vite.config.ts
examples/ssr-spa/package.json
packages/vike-react-query/package.json
packages/vike-react/package.json
pnpm-lock.yaml

[Screen recording 2023-12-06 14.57.02.webm](https://github.com/vikejs/vike-react/assets/1005638/6d9cda01-5ec6-46fc-bb93-bd0d7f7dcf1e)
Thanks to Aurelien's PR https://github.com/vikejs/vike/pull/1271, partial hydration now works 🎉
FYI @nitedani @phonzammi @AurelienLourot

use vike@0.4.149

---

packages/vike-react/renderer/+config.ts
packages/vike-react/renderer/getLang.ts
packages/vike-react/renderer/onRenderClient.tsx
packages/vike-react/renderer/onRenderHtml.tsx
packages/vike-react/renderer/types.d.ts

close #59 
Hi @brillout, @AurelienLourot.
Do we need to be able to updating lang by data hook ?

Updating lang on client-side navigation 

---

packages/vike-react/README.md

Spin-off of https://github.com/vikejs/vike/pull/1455

docs: extend readme

---

packages/vike-react-query/renderer/+config.ts
packages/vike-react/src/+config.ts

fix: set Vike extension name

---

packages/vike-react/src/types/Config.ts

Add children to Wrapper in config

---

packages/vike-react-query/README.md

@nitedani Does this LGTM to you?

docs: improve `vike-react-query` docs

---

examples/full/pages/+Layout.tsx
examples/full/pages/starship/+Layout.tsx
examples/full/pages/starship/+Page.tsx
examples/full/pages/starship/reviews/+Page.tsx
examples/full/pages/starship/spec/+Page.tsx
packages/vike-react/src/+config.ts
packages/vike-react/src/renderer/getPageElement.tsx
packages/vike-react/src/types/Config.ts

Main commit: https://github.com/vikejs/vike-react/commit/92f8da478dbfd60af8a89201065811a59d81b2eb (the other commit merely adds a nested layout example).

feat: make Layout setting cumulative

---

packages/vike-react-query/README.md

FYI @nitedani. (I'll be doing a lot of polishing like that after I'm done with the highest-priority tickets. I think it isn't just worth it, but actually paramount for Vike to grow.)

docs: polish vike-react-query docs

---

packages/vike-react/src/renderer/onRenderClient.tsx

fix: avoid overriding Head setting (fix #135)

---

package.json
packages/vike-react-antd/.gitignore
packages/vike-react-antd/README.md
packages/vike-react-antd/Wrapper.tsx
packages/vike-react-antd/config.ts
packages/vike-react-antd/onAfterRenderHtml.ts
packages/vike-react-antd/onBeforeRenderHtml.ts
packages/vike-react-antd/package.json
packages/vike-react-antd/tsconfig.json
packages/vike-react-chakra/README.md
packages/vike-react/src/types/Config.ts
pnpm-lock.yaml

Hi Rom, here it is – the new extension `vike-react-antd`. Please take a look and review the PR

feat: new extension vike-react-antd

---

package.json
packages/vike-react-styled-components/.gitignore
packages/vike-react-styled-components/README.md
packages/vike-react-styled-components/Wrapper.tsx
packages/vike-react-styled-components/config.ts
packages/vike-react-styled-components/onAfterRenderHtml.ts
packages/vike-react-styled-components/onBeforeRenderHtml.ts
packages/vike-react-styled-components/package.json
packages/vike-react-styled-components/tsconfig.json
pnpm-lock.yaml

Hi Rom, here it is – the new extension `vike-react-styled-components`. Please have a look and review the PR.

feat: new extension `vike-react-styled-components`

---

packages/vike-react-antd/README.md
packages/vike-react-antd/Wrapper.tsx
packages/vike-react-antd/config.ts
packages/vike-react-antd/onAfterRenderHtml.ts
packages/vike-react-antd/onBeforeRenderHtml.ts
packages/vike-react-antd/package.json
packages/vike-react-styled-components/README.md
packages/vike-react-styled-components/Wrapper.tsx
packages/vike-react-styled-components/config.ts
packages/vike-react-styled-components/onAfterRenderHtml.ts
packages/vike-react-styled-components/onBeforeRenderHtml.ts
packages/vike-react-styled-jsx/Wrapper.tsx
packages/vike-react-styled-jsx/onBeforeRenderHtml.ts
pnpm-lock.yaml

In this PR, we make minor changes to refactor the integrations of `vike-react-antd` and `vike-react-styled-components`.
Update:
We also refactor `vike-react-styled-jsx` a bit to simplify conditional logic

Minor refactor of integrations
